import { USER_LOADING, FETCH_USER, fetchUser } from './actions';
import { REPOS_LOADING, FETCH_REPOS, fetchRepos } from './actions';

// let dispatch;
// beforeEach(() => { dispatch = jest.fn(); });

describe('user actions', () => {
  it('creates an action to fetch a user', () => {
    const dispatch = jest.fn();
    const action = fetchUser('sunil');

    return action(dispatch)
      .then(() => {
        expect(dispatch).toHaveBeenCalledWith({ type: USER_LOADING });
        expect(dispatch).toHaveBeenCalledWith({ type: FETCH_USER,
          payload: {
            'login': 'sunil',
            'id': 86241,
            'node_id': 'MDQ6VXNlcjg2MjQx',
            'avatar_url': 'https://avatars2.githubusercontent.com/u/86241?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/sunil',
            'html_url': 'https://github.com/sunil',
            'followers_url': 'https://api.github.com/users/sunil/followers',
            'following_url': 'https://api.github.com/users/sunil/following{/other_user}',
            'gists_url': 'https://api.github.com/users/sunil/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/sunil/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/sunil/subscriptions',
            'organizations_url': 'https://api.github.com/users/sunil/orgs',
            'repos_url': 'https://api.github.com/users/sunil/repos',
            'events_url': 'https://api.github.com/users/sunil/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/sunil/received_events',
            'type': 'User',
            'site_admin': false,
            'name': null,
            'company': null,
            'blog': '',
            'location': null,
            'email': null,
            'hireable': null,
            'bio': null,
            'public_repos': 2,
            'public_gists': 0,
            'followers': 7,
            'following': 0,
            'created_at': '2009-05-19T10:14:18Z',
            'updated_at': '2016-02-26T22:46:11Z'
          }
        });
      });
  });
});

describe('user repo actions', () => {
  it('creates an action to fetch a user\'s repos', () => {
    const dispatch = jest.fn();
    const action = fetchRepos('sunil');

    return action(dispatch)
      .then(() => {
        expect(dispatch).toHaveBeenCalledWith({ type: REPOS_LOADING });
        expect(dispatch).toHaveBeenCalledWith({ type: FETCH_REPOS,
          payload: [
            {
              'archive_url': 'https://api.github.com/repos/sunil/fu/{archive_format}{/ref}',      
              'archived': false,
              'assignees_url': 'https://api.github.com/repos/sunil/fu/assignees{/user}',
              'blobs_url': 'https://api.github.com/repos/sunil/fu/git/blobs{/sha}',
              'branches_url': 'https://api.github.com/repos/sunil/fu/branches{/branch}',
              'clone_url': 'https://github.com/sunil/fu.git',
              'collaborators_url': 'https://api.github.com/repos/sunil/fu/collaborators{/collaborator}',
              'comments_url': 'https://api.github.com/repos/sunil/fu/comments{/number}',
              'commits_url': 'https://api.github.com/repos/sunil/fu/commits{/sha}',
              'compare_url': 'https://api.github.com/repos/sunil/fu/compare/{base}...{head}',     
              'contents_url': 'https://api.github.com/repos/sunil/fu/contents/{+path}',
              'contributors_url': 'https://api.github.com/repos/sunil/fu/contributors',
              'created_at': '2009-05-19T10:15:51Z',
              'default_branch': 'master',
              'deployments_url': 'https://api.github.com/repos/sunil/fu/deployments',
              'description': 'source for the-fu.com django site',
              'disabled': false,
              'downloads_url': 'https://api.github.com/repos/sunil/fu/downloads',
              'events_url': 'https://api.github.com/repos/sunil/fu/events',
              'fork': true,
              'forks': 1,
              'forks_count': 1,
              'forks_url': 'https://api.github.com/repos/sunil/fu/forks',
              'full_name': 'sunil/fu',
              'git_commits_url': 'https://api.github.com/repos/sunil/fu/git/commits{/sha}',       
              'git_refs_url': 'https://api.github.com/repos/sunil/fu/git/refs{/sha}',
              'git_tags_url': 'https://api.github.com/repos/sunil/fu/git/tags{/sha}',
              'git_url': 'git://github.com/sunil/fu.git',
              'has_downloads': true,
              'has_issues': false,
              'has_pages': false,
              'has_projects': true,
              'has_wiki': true,
              'homepage': '',
              'hooks_url': 'https://api.github.com/repos/sunil/fu/hooks',
              'html_url': 'https://github.com/sunil/fu',
              'id': 204715,
              'issue_comment_url': 'https://api.github.com/repos/sunil/fu/issues/comments{/number}',
              'issue_events_url': 'https://api.github.com/repos/sunil/fu/issues/events{/number}', 
              'issues_url': 'https://api.github.com/repos/sunil/fu/issues{/number}',
              'keys_url': 'https://api.github.com/repos/sunil/fu/keys{/key_id}',
              'labels_url': 'https://api.github.com/repos/sunil/fu/labels{/name}',
              'language': null,
              'languages_url': 'https://api.github.com/repos/sunil/fu/languages',
              'license': null,
              'merges_url': 'https://api.github.com/repos/sunil/fu/merges',
              'milestones_url': 'https://api.github.com/repos/sunil/fu/milestones{/number}',      
              'mirror_url': null,
              'name': 'fu',
              'node_id': 'MDEwOlJlcG9zaXRvcnkyMDQ3MTU=',
              'notifications_url': 'https://api.github.com/repos/sunil/fu/notifications{?since,all,participating}',
              'open_issues': 0,
              'open_issues_count': 0,
              'owner': {
                'avatar_url': 'https://avatars2.githubusercontent.com/u/86241?v=4',
                'events_url': 'https://api.github.com/users/sunil/events{/privacy}',
                'followers_url': 'https://api.github.com/users/sunil/followers',
                'following_url': 'https://api.github.com/users/sunil/following{/other_user}',     
                'gists_url': 'https://api.github.com/users/sunil/gists{/gist_id}',
                'gravatar_id': '',
                'html_url': 'https://github.com/sunil',
                'id': 86241,
                'login': 'sunil',
                'node_id': 'MDQ6VXNlcjg2MjQx',
                'organizations_url': 'https://api.github.com/users/sunil/orgs',
                'received_events_url': 'https://api.github.com/users/sunil/received_events',      
                'repos_url': 'https://api.github.com/users/sunil/repos',
                'site_admin': false,
                'starred_url': 'https://api.github.com/users/sunil/starred{/owner}{/repo}',       
                'subscriptions_url': 'https://api.github.com/users/sunil/subscriptions',
                'type': 'User',
                'url': 'https://api.github.com/users/sunil',
              },
              'private': false,
              'pulls_url': 'https://api.github.com/repos/sunil/fu/pulls{/number}',
              'pushed_at': '2008-12-10T19:18:28Z',
              'releases_url': 'https://api.github.com/repos/sunil/fu/releases{/id}',
              'size': 15778,
              'ssh_url': 'git@github.com:sunil/fu.git',
              'stargazers_count': 1,
              'stargazers_url': 'https://api.github.com/repos/sunil/fu/stargazers',
              'statuses_url': 'https://api.github.com/repos/sunil/fu/statuses/{sha}',
              'subscribers_url': 'https://api.github.com/repos/sunil/fu/subscribers',
              'subscription_url': 'https://api.github.com/repos/sunil/fu/subscription',
              'svn_url': 'https://github.com/sunil/fu',
              'tags_url': 'https://api.github.com/repos/sunil/fu/tags',
              'teams_url': 'https://api.github.com/repos/sunil/fu/teams',
              'trees_url': 'https://api.github.com/repos/sunil/fu/git/trees{/sha}',
              'updated_at': '2012-12-12T22:10:40Z',
              'url': 'https://api.github.com/repos/sunil/fu',
              'watchers': 1,
              'watchers_count': 1,
            },
            {
              'archive_url': 'https://api.github.com/repos/sunil/KUV/{archive_format}{/ref}',     
              'archived': false,
              'assignees_url': 'https://api.github.com/repos/sunil/KUV/assignees{/user}',
              'blobs_url': 'https://api.github.com/repos/sunil/KUV/git/blobs{/sha}',
              'branches_url': 'https://api.github.com/repos/sunil/KUV/branches{/branch}',
              'clone_url': 'https://github.com/sunil/KUV.git',
              'collaborators_url': 'https://api.github.com/repos/sunil/KUV/collaborators{/collaborator}',
              'comments_url': 'https://api.github.com/repos/sunil/KUV/comments{/number}',
              'commits_url': 'https://api.github.com/repos/sunil/KUV/commits{/sha}',
              'compare_url': 'https://api.github.com/repos/sunil/KUV/compare/{base}...{head}',    
              'contents_url': 'https://api.github.com/repos/sunil/KUV/contents/{+path}',
              'contributors_url': 'https://api.github.com/repos/sunil/KUV/contributors',
              'created_at': '2013-08-31T18:59:57Z',
              'default_branch': 'master',
              'deployments_url': 'https://api.github.com/repos/sunil/KUV/deployments',
              'description': 'Porject KUV repository',
              'disabled': false,
              'downloads_url': 'https://api.github.com/repos/sunil/KUV/downloads',
              'events_url': 'https://api.github.com/repos/sunil/KUV/events',
              'fork': false,
              'forks': 0,
              'forks_count': 0,
              'forks_url': 'https://api.github.com/repos/sunil/KUV/forks',
              'full_name': 'sunil/KUV',
              'git_commits_url': 'https://api.github.com/repos/sunil/KUV/git/commits{/sha}',      
              'git_refs_url': 'https://api.github.com/repos/sunil/KUV/git/refs{/sha}',
              'git_tags_url': 'https://api.github.com/repos/sunil/KUV/git/tags{/sha}',
              'git_url': 'git://github.com/sunil/KUV.git',
              'has_downloads': true,
              'has_issues': true,
              'has_pages': false,
              'has_projects': true,
              'has_wiki': true,
              'homepage': null,
              'hooks_url': 'https://api.github.com/repos/sunil/KUV/hooks',
              'html_url': 'https://github.com/sunil/KUV',
              'id': 12510190,
              'issue_comment_url': 'https://api.github.com/repos/sunil/KUV/issues/comments{/number}',
              'issue_events_url': 'https://api.github.com/repos/sunil/KUV/issues/events{/number}',
              'issues_url': 'https://api.github.com/repos/sunil/KUV/issues{/number}',
              'keys_url': 'https://api.github.com/repos/sunil/KUV/keys{/key_id}',
              'labels_url': 'https://api.github.com/repos/sunil/KUV/labels{/name}',
              'language': null,
              'languages_url': 'https://api.github.com/repos/sunil/KUV/languages',
              'license': null,
              'merges_url': 'https://api.github.com/repos/sunil/KUV/merges',
              'milestones_url': 'https://api.github.com/repos/sunil/KUV/milestones{/number}',     
              'mirror_url': null,
              'name': 'KUV',
              'node_id': 'MDEwOlJlcG9zaXRvcnkxMjUxMDE5MA==',
              'notifications_url': 'https://api.github.com/repos/sunil/KUV/notifications{?since,all,participating}',
              'open_issues': 0,
              'open_issues_count': 0,
              'owner': {
                'avatar_url': 'https://avatars2.githubusercontent.com/u/86241?v=4',
                'events_url': 'https://api.github.com/users/sunil/events{/privacy}',
                'followers_url': 'https://api.github.com/users/sunil/followers',
                'following_url': 'https://api.github.com/users/sunil/following{/other_user}',     
                'gists_url': 'https://api.github.com/users/sunil/gists{/gist_id}',
                'gravatar_id': '',
                'html_url': 'https://github.com/sunil',
                'id': 86241,
                'login': 'sunil',
                'node_id': 'MDQ6VXNlcjg2MjQx',
                'organizations_url': 'https://api.github.com/users/sunil/orgs',
                'received_events_url': 'https://api.github.com/users/sunil/received_events',      
                'repos_url': 'https://api.github.com/users/sunil/repos',
                'site_admin': false,
                'starred_url': 'https://api.github.com/users/sunil/starred{/owner}{/repo}',       
                'subscriptions_url': 'https://api.github.com/users/sunil/subscriptions',
                'type': 'User',
                'url': 'https://api.github.com/users/sunil',
              },
              'private': false,
              'pulls_url': 'https://api.github.com/repos/sunil/KUV/pulls{/number}',
              'pushed_at': '2013-08-31T18:59:57Z',
              'releases_url': 'https://api.github.com/repos/sunil/KUV/releases{/id}',
              'size': 56,
              'ssh_url': 'git@github.com:sunil/KUV.git',
              'stargazers_count': 0,
              'stargazers_url': 'https://api.github.com/repos/sunil/KUV/stargazers',
              'statuses_url': 'https://api.github.com/repos/sunil/KUV/statuses/{sha}',
              'subscribers_url': 'https://api.github.com/repos/sunil/KUV/subscribers',
              'subscription_url': 'https://api.github.com/repos/sunil/KUV/subscription',
              'svn_url': 'https://github.com/sunil/KUV',
              'tags_url': 'https://api.github.com/repos/sunil/KUV/tags',
              'teams_url': 'https://api.github.com/repos/sunil/KUV/teams',
              'trees_url': 'https://api.github.com/repos/sunil/KUV/git/trees{/sha}',
              'updated_at': '2013-08-31T18:59:57Z',
              'url': 'https://api.github.com/repos/sunil/KUV',
              'watchers': 0,
              'watchers_count': 0,
            }
          ]
        });
      });
  });
});
