import { REPOS_LOADING, FETCH_REPOS } from '../actions/actions';
import reducer from './reposReducer';

describe('repos reducer', () => {
  it('handles the repos loading action', () => {
    const action = { type: REPOS_LOADING };
    const initialState = { loading: false };

    const newState = reducer(initialState, action);
    expect(newState).toEqual({ loading: true });
  });

  it('handles the fetch repos action', () => {
    const action = {
      type: FETCH_REPOS,
      payload: [
        {
          'id': 204715,
          'node_id': 'MDEwOlJlcG9zaXRvcnkyMDQ3MTU=',
          'name': 'fu',
          'full_name': 'sunil/fu',
          'private': false,
          'owner': {
            'login': 'sunil',
            'id': 86241,
            'node_id': 'MDQ6VXNlcjg2MjQx',
            'avatar_url': 'https://avatars2.githubusercontent.com/u/86241?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/sunil',
            'html_url': 'https://github.com/sunil',
            'followers_url': 'https://api.github.com/users/sunil/followers',
            'following_url': 'https://api.github.com/users/sunil/following{/other_user}',
            'gists_url': 'https://api.github.com/users/sunil/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/sunil/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/sunil/subscriptions',
            'organizations_url': 'https://api.github.com/users/sunil/orgs',
            'repos_url': 'https://api.github.com/users/sunil/repos',
            'events_url': 'https://api.github.com/users/sunil/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/sunil/received_events',
            'type': 'User',
            'site_admin': false
          },
          'html_url': 'https://github.com/sunil/fu',
          'description': 'source for the-fu.com django site',
          'fork': true,
          'url': 'https://api.github.com/repos/sunil/fu',
          'forks_url': 'https://api.github.com/repos/sunil/fu/forks',
          'keys_url': 'https://api.github.com/repos/sunil/fu/keys{/key_id}',
          'collaborators_url': 'https://api.github.com/repos/sunil/fu/collaborators{/collaborator}',
          'teams_url': 'https://api.github.com/repos/sunil/fu/teams',
          'hooks_url': 'https://api.github.com/repos/sunil/fu/hooks',
          'issue_events_url': 'https://api.github.com/repos/sunil/fu/issues/events{/number}',
          'events_url': 'https://api.github.com/repos/sunil/fu/events',
          'assignees_url': 'https://api.github.com/repos/sunil/fu/assignees{/user}',
          'branches_url': 'https://api.github.com/repos/sunil/fu/branches{/branch}',
          'tags_url': 'https://api.github.com/repos/sunil/fu/tags',
          'blobs_url': 'https://api.github.com/repos/sunil/fu/git/blobs{/sha}',
          'git_tags_url': 'https://api.github.com/repos/sunil/fu/git/tags{/sha}',
          'git_refs_url': 'https://api.github.com/repos/sunil/fu/git/refs{/sha}',
          'trees_url': 'https://api.github.com/repos/sunil/fu/git/trees{/sha}',
          'statuses_url': 'https://api.github.com/repos/sunil/fu/statuses/{sha}',
          'languages_url': 'https://api.github.com/repos/sunil/fu/languages',
          'stargazers_url': 'https://api.github.com/repos/sunil/fu/stargazers',
          'contributors_url': 'https://api.github.com/repos/sunil/fu/contributors',
          'subscribers_url': 'https://api.github.com/repos/sunil/fu/subscribers',
          'subscription_url': 'https://api.github.com/repos/sunil/fu/subscription',
          'commits_url': 'https://api.github.com/repos/sunil/fu/commits{/sha}',
          'git_commits_url': 'https://api.github.com/repos/sunil/fu/git/commits{/sha}',
          'comments_url': 'https://api.github.com/repos/sunil/fu/comments{/number}',
          'issue_comment_url': 'https://api.github.com/repos/sunil/fu/issues/comments{/number}',
          'contents_url': 'https://api.github.com/repos/sunil/fu/contents/{+path}',
          'compare_url': 'https://api.github.com/repos/sunil/fu/compare/{base}...{head}',
          'merges_url': 'https://api.github.com/repos/sunil/fu/merges',
          'archive_url': 'https://api.github.com/repos/sunil/fu/{archive_format}{/ref}',
          'downloads_url': 'https://api.github.com/repos/sunil/fu/downloads',
          'issues_url': 'https://api.github.com/repos/sunil/fu/issues{/number}',
          'pulls_url': 'https://api.github.com/repos/sunil/fu/pulls{/number}',
          'milestones_url': 'https://api.github.com/repos/sunil/fu/milestones{/number}',
          'notifications_url': 'https://api.github.com/repos/sunil/fu/notifications{?since,all,participating}',
          'labels_url': 'https://api.github.com/repos/sunil/fu/labels{/name}',
          'releases_url': 'https://api.github.com/repos/sunil/fu/releases{/id}',
          'deployments_url': 'https://api.github.com/repos/sunil/fu/deployments',
          'created_at': '2009-05-19T10:15:51Z',
          'updated_at': '2012-12-12T22:10:40Z',
          'pushed_at': '2008-12-10T19:18:28Z',
          'git_url': 'git://github.com/sunil/fu.git',
          'ssh_url': 'git@github.com:sunil/fu.git',
          'clone_url': 'https://github.com/sunil/fu.git',
          'svn_url': 'https://github.com/sunil/fu',
          'homepage': '',
          'size': 15778,
          'stargazers_count': 1,
          'watchers_count': 1,
          'language': null,
          'has_issues': false,
          'has_projects': true,
          'has_downloads': true,
          'has_wiki': true,
          'has_pages': false,
          'forks_count': 1,
          'mirror_url': null,
          'archived': false,
          'disabled': false,
          'open_issues_count': 0,
          'license': null,
          'forks': 1,
          'open_issues': 0,
          'watchers': 1,
          'default_branch': 'master'
        },
        {
          'id': 12510190,
          'node_id': 'MDEwOlJlcG9zaXRvcnkxMjUxMDE5MA==',
          'name': 'KUV',
          'full_name': 'sunil/KUV',
          'private': false,
          'owner': {
            'login': 'sunil',
            'id': 86241,
            'node_id': 'MDQ6VXNlcjg2MjQx',
            'avatar_url': 'https://avatars2.githubusercontent.com/u/86241?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/sunil',
            'html_url': 'https://github.com/sunil',
            'followers_url': 'https://api.github.com/users/sunil/followers',
            'following_url': 'https://api.github.com/users/sunil/following{/other_user}',
            'gists_url': 'https://api.github.com/users/sunil/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/sunil/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/sunil/subscriptions',
            'organizations_url': 'https://api.github.com/users/sunil/orgs',
            'repos_url': 'https://api.github.com/users/sunil/repos',
            'events_url': 'https://api.github.com/users/sunil/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/sunil/received_events',
            'type': 'User',
            'site_admin': false
          },
          'html_url': 'https://github.com/sunil/KUV',
          'description': 'Porject KUV repository',
          'fork': false,
          'url': 'https://api.github.com/repos/sunil/KUV',
          'forks_url': 'https://api.github.com/repos/sunil/KUV/forks',
          'keys_url': 'https://api.github.com/repos/sunil/KUV/keys{/key_id}',
          'collaborators_url': 'https://api.github.com/repos/sunil/KUV/collaborators{/collaborator}',
          'teams_url': 'https://api.github.com/repos/sunil/KUV/teams',
          'hooks_url': 'https://api.github.com/repos/sunil/KUV/hooks',
          'issue_events_url': 'https://api.github.com/repos/sunil/KUV/issues/events{/number}',
          'events_url': 'https://api.github.com/repos/sunil/KUV/events',
          'assignees_url': 'https://api.github.com/repos/sunil/KUV/assignees{/user}',
          'branches_url': 'https://api.github.com/repos/sunil/KUV/branches{/branch}',
          'tags_url': 'https://api.github.com/repos/sunil/KUV/tags',
          'blobs_url': 'https://api.github.com/repos/sunil/KUV/git/blobs{/sha}',
          'git_tags_url': 'https://api.github.com/repos/sunil/KUV/git/tags{/sha}',
          'git_refs_url': 'https://api.github.com/repos/sunil/KUV/git/refs{/sha}',
          'trees_url': 'https://api.github.com/repos/sunil/KUV/git/trees{/sha}',
          'statuses_url': 'https://api.github.com/repos/sunil/KUV/statuses/{sha}',
          'languages_url': 'https://api.github.com/repos/sunil/KUV/languages',
          'stargazers_url': 'https://api.github.com/repos/sunil/KUV/stargazers',
          'contributors_url': 'https://api.github.com/repos/sunil/KUV/contributors',
          'subscribers_url': 'https://api.github.com/repos/sunil/KUV/subscribers',
          'subscription_url': 'https://api.github.com/repos/sunil/KUV/subscription',
          'commits_url': 'https://api.github.com/repos/sunil/KUV/commits{/sha}',
          'git_commits_url': 'https://api.github.com/repos/sunil/KUV/git/commits{/sha}',
          'comments_url': 'https://api.github.com/repos/sunil/KUV/comments{/number}',
          'issue_comment_url': 'https://api.github.com/repos/sunil/KUV/issues/comments{/number}',
          'contents_url': 'https://api.github.com/repos/sunil/KUV/contents/{+path}',
          'compare_url': 'https://api.github.com/repos/sunil/KUV/compare/{base}...{head}',
          'merges_url': 'https://api.github.com/repos/sunil/KUV/merges',
          'archive_url': 'https://api.github.com/repos/sunil/KUV/{archive_format}{/ref}',
          'downloads_url': 'https://api.github.com/repos/sunil/KUV/downloads',
          'issues_url': 'https://api.github.com/repos/sunil/KUV/issues{/number}',
          'pulls_url': 'https://api.github.com/repos/sunil/KUV/pulls{/number}',
          'milestones_url': 'https://api.github.com/repos/sunil/KUV/milestones{/number}',
          'notifications_url': 'https://api.github.com/repos/sunil/KUV/notifications{?since,all,participating}',
          'labels_url': 'https://api.github.com/repos/sunil/KUV/labels{/name}',
          'releases_url': 'https://api.github.com/repos/sunil/KUV/releases{/id}',
          'deployments_url': 'https://api.github.com/repos/sunil/KUV/deployments',
          'created_at': '2013-08-31T18:59:57Z',
          'updated_at': '2013-08-31T18:59:57Z',
          'pushed_at': '2013-08-31T18:59:57Z',
          'git_url': 'git://github.com/sunil/KUV.git',
          'ssh_url': 'git@github.com:sunil/KUV.git',
          'clone_url': 'https://github.com/sunil/KUV.git',
          'svn_url': 'https://github.com/sunil/KUV',
          'homepage': null,
          'size': 56,
          'stargazers_count': 0,
          'watchers_count': 0,
          'language': null,
          'has_issues': true,
          'has_projects': true,
          'has_downloads': true,
          'has_wiki': true,
          'has_pages': false,
          'forks_count': 0,
          'mirror_url': null,
          'archived': false,
          'disabled': false,
          'open_issues_count': 0,
          'license': null,
          'forks': 0,
          'open_issues': 0,
          'watchers': 0,
          'default_branch': 'master'
        }
      ]      
    };
    const initialState = { loading: true, allRepos: null };
    const newState = reducer(initialState, action);

    expect(newState).toEqual({
      loading: false,
      allRepos: [
        {
          'id': 204715,
          'node_id': 'MDEwOlJlcG9zaXRvcnkyMDQ3MTU=',
          'name': 'fu',
          'full_name': 'sunil/fu',
          'private': false,
          'owner': {
            'login': 'sunil',
            'id': 86241,
            'node_id': 'MDQ6VXNlcjg2MjQx',
            'avatar_url': 'https://avatars2.githubusercontent.com/u/86241?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/sunil',
            'html_url': 'https://github.com/sunil',
            'followers_url': 'https://api.github.com/users/sunil/followers',
            'following_url': 'https://api.github.com/users/sunil/following{/other_user}',
            'gists_url': 'https://api.github.com/users/sunil/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/sunil/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/sunil/subscriptions',
            'organizations_url': 'https://api.github.com/users/sunil/orgs',
            'repos_url': 'https://api.github.com/users/sunil/repos',
            'events_url': 'https://api.github.com/users/sunil/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/sunil/received_events',
            'type': 'User',
            'site_admin': false
          },
          'html_url': 'https://github.com/sunil/fu',
          'description': 'source for the-fu.com django site',
          'fork': true,
          'url': 'https://api.github.com/repos/sunil/fu',
          'forks_url': 'https://api.github.com/repos/sunil/fu/forks',
          'keys_url': 'https://api.github.com/repos/sunil/fu/keys{/key_id}',
          'collaborators_url': 'https://api.github.com/repos/sunil/fu/collaborators{/collaborator}',
          'teams_url': 'https://api.github.com/repos/sunil/fu/teams',
          'hooks_url': 'https://api.github.com/repos/sunil/fu/hooks',
          'issue_events_url': 'https://api.github.com/repos/sunil/fu/issues/events{/number}',
          'events_url': 'https://api.github.com/repos/sunil/fu/events',
          'assignees_url': 'https://api.github.com/repos/sunil/fu/assignees{/user}',
          'branches_url': 'https://api.github.com/repos/sunil/fu/branches{/branch}',
          'tags_url': 'https://api.github.com/repos/sunil/fu/tags',
          'blobs_url': 'https://api.github.com/repos/sunil/fu/git/blobs{/sha}',
          'git_tags_url': 'https://api.github.com/repos/sunil/fu/git/tags{/sha}',
          'git_refs_url': 'https://api.github.com/repos/sunil/fu/git/refs{/sha}',
          'trees_url': 'https://api.github.com/repos/sunil/fu/git/trees{/sha}',
          'statuses_url': 'https://api.github.com/repos/sunil/fu/statuses/{sha}',
          'languages_url': 'https://api.github.com/repos/sunil/fu/languages',
          'stargazers_url': 'https://api.github.com/repos/sunil/fu/stargazers',
          'contributors_url': 'https://api.github.com/repos/sunil/fu/contributors',
          'subscribers_url': 'https://api.github.com/repos/sunil/fu/subscribers',
          'subscription_url': 'https://api.github.com/repos/sunil/fu/subscription',
          'commits_url': 'https://api.github.com/repos/sunil/fu/commits{/sha}',
          'git_commits_url': 'https://api.github.com/repos/sunil/fu/git/commits{/sha}',
          'comments_url': 'https://api.github.com/repos/sunil/fu/comments{/number}',
          'issue_comment_url': 'https://api.github.com/repos/sunil/fu/issues/comments{/number}',
          'contents_url': 'https://api.github.com/repos/sunil/fu/contents/{+path}',
          'compare_url': 'https://api.github.com/repos/sunil/fu/compare/{base}...{head}',
          'merges_url': 'https://api.github.com/repos/sunil/fu/merges',
          'archive_url': 'https://api.github.com/repos/sunil/fu/{archive_format}{/ref}',
          'downloads_url': 'https://api.github.com/repos/sunil/fu/downloads',
          'issues_url': 'https://api.github.com/repos/sunil/fu/issues{/number}',
          'pulls_url': 'https://api.github.com/repos/sunil/fu/pulls{/number}',
          'milestones_url': 'https://api.github.com/repos/sunil/fu/milestones{/number}',
          'notifications_url': 'https://api.github.com/repos/sunil/fu/notifications{?since,all,participating}',
          'labels_url': 'https://api.github.com/repos/sunil/fu/labels{/name}',
          'releases_url': 'https://api.github.com/repos/sunil/fu/releases{/id}',
          'deployments_url': 'https://api.github.com/repos/sunil/fu/deployments',
          'created_at': '2009-05-19T10:15:51Z',
          'updated_at': '2012-12-12T22:10:40Z',
          'pushed_at': '2008-12-10T19:18:28Z',
          'git_url': 'git://github.com/sunil/fu.git',
          'ssh_url': 'git@github.com:sunil/fu.git',
          'clone_url': 'https://github.com/sunil/fu.git',
          'svn_url': 'https://github.com/sunil/fu',
          'homepage': '',
          'size': 15778,
          'stargazers_count': 1,
          'watchers_count': 1,
          'language': null,
          'has_issues': false,
          'has_projects': true,
          'has_downloads': true,
          'has_wiki': true,
          'has_pages': false,
          'forks_count': 1,
          'mirror_url': null,
          'archived': false,
          'disabled': false,
          'open_issues_count': 0,
          'license': null,
          'forks': 1,
          'open_issues': 0,
          'watchers': 1,
          'default_branch': 'master'
        },
        {
          'id': 12510190,
          'node_id': 'MDEwOlJlcG9zaXRvcnkxMjUxMDE5MA==',
          'name': 'KUV',
          'full_name': 'sunil/KUV',
          'private': false,
          'owner': {
            'login': 'sunil',
            'id': 86241,
            'node_id': 'MDQ6VXNlcjg2MjQx',
            'avatar_url': 'https://avatars2.githubusercontent.com/u/86241?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/sunil',
            'html_url': 'https://github.com/sunil',
            'followers_url': 'https://api.github.com/users/sunil/followers',
            'following_url': 'https://api.github.com/users/sunil/following{/other_user}',
            'gists_url': 'https://api.github.com/users/sunil/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/sunil/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/sunil/subscriptions',
            'organizations_url': 'https://api.github.com/users/sunil/orgs',
            'repos_url': 'https://api.github.com/users/sunil/repos',
            'events_url': 'https://api.github.com/users/sunil/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/sunil/received_events',
            'type': 'User',
            'site_admin': false
          },
          'html_url': 'https://github.com/sunil/KUV',
          'description': 'Porject KUV repository',
          'fork': false,
          'url': 'https://api.github.com/repos/sunil/KUV',
          'forks_url': 'https://api.github.com/repos/sunil/KUV/forks',
          'keys_url': 'https://api.github.com/repos/sunil/KUV/keys{/key_id}',
          'collaborators_url': 'https://api.github.com/repos/sunil/KUV/collaborators{/collaborator}',
          'teams_url': 'https://api.github.com/repos/sunil/KUV/teams',
          'hooks_url': 'https://api.github.com/repos/sunil/KUV/hooks',
          'issue_events_url': 'https://api.github.com/repos/sunil/KUV/issues/events{/number}',
          'events_url': 'https://api.github.com/repos/sunil/KUV/events',
          'assignees_url': 'https://api.github.com/repos/sunil/KUV/assignees{/user}',
          'branches_url': 'https://api.github.com/repos/sunil/KUV/branches{/branch}',
          'tags_url': 'https://api.github.com/repos/sunil/KUV/tags',
          'blobs_url': 'https://api.github.com/repos/sunil/KUV/git/blobs{/sha}',
          'git_tags_url': 'https://api.github.com/repos/sunil/KUV/git/tags{/sha}',
          'git_refs_url': 'https://api.github.com/repos/sunil/KUV/git/refs{/sha}',
          'trees_url': 'https://api.github.com/repos/sunil/KUV/git/trees{/sha}',
          'statuses_url': 'https://api.github.com/repos/sunil/KUV/statuses/{sha}',
          'languages_url': 'https://api.github.com/repos/sunil/KUV/languages',
          'stargazers_url': 'https://api.github.com/repos/sunil/KUV/stargazers',
          'contributors_url': 'https://api.github.com/repos/sunil/KUV/contributors',
          'subscribers_url': 'https://api.github.com/repos/sunil/KUV/subscribers',
          'subscription_url': 'https://api.github.com/repos/sunil/KUV/subscription',
          'commits_url': 'https://api.github.com/repos/sunil/KUV/commits{/sha}',
          'git_commits_url': 'https://api.github.com/repos/sunil/KUV/git/commits{/sha}',
          'comments_url': 'https://api.github.com/repos/sunil/KUV/comments{/number}',
          'issue_comment_url': 'https://api.github.com/repos/sunil/KUV/issues/comments{/number}',
          'contents_url': 'https://api.github.com/repos/sunil/KUV/contents/{+path}',
          'compare_url': 'https://api.github.com/repos/sunil/KUV/compare/{base}...{head}',
          'merges_url': 'https://api.github.com/repos/sunil/KUV/merges',
          'archive_url': 'https://api.github.com/repos/sunil/KUV/{archive_format}{/ref}',
          'downloads_url': 'https://api.github.com/repos/sunil/KUV/downloads',
          'issues_url': 'https://api.github.com/repos/sunil/KUV/issues{/number}',
          'pulls_url': 'https://api.github.com/repos/sunil/KUV/pulls{/number}',
          'milestones_url': 'https://api.github.com/repos/sunil/KUV/milestones{/number}',
          'notifications_url': 'https://api.github.com/repos/sunil/KUV/notifications{?since,all,participating}',
          'labels_url': 'https://api.github.com/repos/sunil/KUV/labels{/name}',
          'releases_url': 'https://api.github.com/repos/sunil/KUV/releases{/id}',
          'deployments_url': 'https://api.github.com/repos/sunil/KUV/deployments',
          'created_at': '2013-08-31T18:59:57Z',
          'updated_at': '2013-08-31T18:59:57Z',
          'pushed_at': '2013-08-31T18:59:57Z',
          'git_url': 'git://github.com/sunil/KUV.git',
          'ssh_url': 'git@github.com:sunil/KUV.git',
          'clone_url': 'https://github.com/sunil/KUV.git',
          'svn_url': 'https://github.com/sunil/KUV',
          'homepage': null,
          'size': 56,
          'stargazers_count': 0,
          'watchers_count': 0,
          'language': null,
          'has_issues': true,
          'has_projects': true,
          'has_downloads': true,
          'has_wiki': true,
          'has_pages': false,
          'forks_count': 0,
          'mirror_url': null,
          'archived': false,
          'disabled': false,
          'open_issues_count': 0,
          'license': null,
          'forks': 0,
          'open_issues': 0,
          'watchers': 0,
          'default_branch': 'master'
        }
      ]      
    });
  });
});
