import { isReposLoading, selectRepos } from './reposSelector';

describe('repos selectors', () => {
  it('selects the repo loading state', () => {
    const state = {
      repos: {
        loading: true,
      }
    };

    expect(isReposLoading (state)).toEqual(true);
  });

  it('selects allRepos state', () => {
    const state = {
      repos: {
        allRepos: [
          {
            'id': 207071105,
            'node_id': 'MDEwOlJlcG9zaXRvcnkyMDcwNzExMDU=',
            'name': 'acts-as-taggable-on',
            'full_name': 'john/acts-as-taggable-on',
            'private': false,
            'owner': {
              'login': 'john',
              'id': 1668,
              'node_id': 'MDQ6VXNlcjE2Njg=',
              'avatar_url': 'https://avatars1.githubusercontent.com/u/1668?v=4',
              'gravatar_id': '',
              'url': 'https://api.github.com/users/john',
              'html_url': 'https://github.com/john',
              'followers_url': 'https://api.github.com/users/john/followers',
              'following_url': 'https://api.github.com/users/john/following{/other_user}',
              'gists_url': 'https://api.github.com/users/john/gists{/gist_id}',
              'starred_url': 'https://api.github.com/users/john/starred{/owner}{/repo}',
              'subscriptions_url': 'https://api.github.com/users/john/subscriptions',
              'organizations_url': 'https://api.github.com/users/john/orgs',
              'repos_url': 'https://api.github.com/users/john/repos',
              'events_url': 'https://api.github.com/users/john/events{/privacy}',
              'received_events_url': 'https://api.github.com/users/john/received_events',
              'type': 'User',
              'site_admin': false
            },
            'html_url': 'https://github.com/john/acts-as-taggable-on',
            'description': 'A tagging plugin for Rails applications that allows for custom tagging along dynamic contexts.',
            'fork': true,
            'url': 'https://api.github.com/repos/john/acts-as-taggable-on',
            'forks_url': 'https://api.github.com/repos/john/acts-as-taggable-on/forks',
            'keys_url': 'https://api.github.com/repos/john/acts-as-taggable-on/keys{/key_id}',
            'collaborators_url': 'https://api.github.com/repos/john/acts-as-taggable-on/collaborators{/collaborator}',
            'teams_url': 'https://api.github.com/repos/john/acts-as-taggable-on/teams',
            'hooks_url': 'https://api.github.com/repos/john/acts-as-taggable-on/hooks',
            'issue_events_url': 'https://api.github.com/repos/john/acts-as-taggable-on/issues/events{/number}',
            'events_url': 'https://api.github.com/repos/john/acts-as-taggable-on/events',
            'assignees_url': 'https://api.github.com/repos/john/acts-as-taggable-on/assignees{/user}',
            'branches_url': 'https://api.github.com/repos/john/acts-as-taggable-on/branches{/branch}',
            'tags_url': 'https://api.github.com/repos/john/acts-as-taggable-on/tags',
            'blobs_url': 'https://api.github.com/repos/john/acts-as-taggable-on/git/blobs{/sha}',
            'git_tags_url': 'https://api.github.com/repos/john/acts-as-taggable-on/git/tags{/sha}',
            'git_refs_url': 'https://api.github.com/repos/john/acts-as-taggable-on/git/refs{/sha}',
            'trees_url': 'https://api.github.com/repos/john/acts-as-taggable-on/git/trees{/sha}',
            'statuses_url': 'https://api.github.com/repos/john/acts-as-taggable-on/statuses/{sha}',
            'languages_url': 'https://api.github.com/repos/john/acts-as-taggable-on/languages',
            'stargazers_url': 'https://api.github.com/repos/john/acts-as-taggable-on/stargazers',
            'contributors_url': 'https://api.github.com/repos/john/acts-as-taggable-on/contributors',
            'subscribers_url': 'https://api.github.com/repos/john/acts-as-taggable-on/subscribers',
            'subscription_url': 'https://api.github.com/repos/john/acts-as-taggable-on/subscription',
            'commits_url': 'https://api.github.com/repos/john/acts-as-taggable-on/commits{/sha}',
            'git_commits_url': 'https://api.github.com/repos/john/acts-as-taggable-on/git/commits{/sha}',
            'comments_url': 'https://api.github.com/repos/john/acts-as-taggable-on/comments{/number}',
            'issue_comment_url': 'https://api.github.com/repos/john/acts-as-taggable-on/issues/comments{/number}',
            'contents_url': 'https://api.github.com/repos/john/acts-as-taggable-on/contents/{+path}',
            'compare_url': 'https://api.github.com/repos/john/acts-as-taggable-on/compare/{base}...{head}',
            'merges_url': 'https://api.github.com/repos/john/acts-as-taggable-on/merges',
            'archive_url': 'https://api.github.com/repos/john/acts-as-taggable-on/{archive_format}{/ref}',
            'downloads_url': 'https://api.github.com/repos/john/acts-as-taggable-on/downloads',
            'issues_url': 'https://api.github.com/repos/john/acts-as-taggable-on/issues{/number}',
            'pulls_url': 'https://api.github.com/repos/john/acts-as-taggable-on/pulls{/number}',
            'milestones_url': 'https://api.github.com/repos/john/acts-as-taggable-on/milestones{/number}',
            'notifications_url': 'https://api.github.com/repos/john/acts-as-taggable-on/notifications{?since,all,participating}',
            'labels_url': 'https://api.github.com/repos/john/acts-as-taggable-on/labels{/name}',
            'releases_url': 'https://api.github.com/repos/john/acts-as-taggable-on/releases{/id}',
            'deployments_url': 'https://api.github.com/repos/john/acts-as-taggable-on/deployments',
            'created_at': '2019-09-08T06:23:42Z',
            'updated_at': '2019-09-08T06:24:54Z',
            'pushed_at': '2019-09-08T06:24:50Z',
            'git_url': 'git://github.com/john/acts-as-taggable-on.git',
            'ssh_url': 'git@github.com:john/acts-as-taggable-on.git',
            'clone_url': 'https://github.com/john/acts-as-taggable-on.git',
            'svn_url': 'https://github.com/john/acts-as-taggable-on',
            'homepage': 'http://mbleigh.lighthouseapp.com/projects/10116-acts-as-taggable-on',
            'size': 1155,
            'stargazers_count': 0,
            'watchers_count': 0,
            'language': 'Ruby',
            'has_issues': false,
            'has_projects': true,
            'has_downloads': true,
            'has_wiki': true,
            'has_pages': false,
            'forks_count': 1,
            'mirror_url': null,
            'archived': false,
            'disabled': false,
            'open_issues_count': 0,
            'license': {
              'key': 'other',
              'name': 'Other',
              'spdx_id': 'NOASSERTION',
              'url': null,
              'node_id': 'MDc6TGljZW5zZTA='
            },
            'forks': 1,
            'open_issues': 0,
            'watchers': 0,
            'default_branch': 'master'
          },
          {
            'id': 23097215,
            'node_id': 'MDEwOlJlcG9zaXRvcnkyMzA5NzIxNQ==',
            'name': 'acts_as_commentable_with_threading',
            'full_name': 'john/acts_as_commentable_with_threading',
            'private': false,
            'owner': {
              'login': 'john',
              'id': 1668,
              'node_id': 'MDQ6VXNlcjE2Njg=',
              'avatar_url': 'https://avatars1.githubusercontent.com/u/1668?v=4',
              'gravatar_id': '',
              'url': 'https://api.github.com/users/john',
              'html_url': 'https://github.com/john',
              'followers_url': 'https://api.github.com/users/john/followers',
              'following_url': 'https://api.github.com/users/john/following{/other_user}',
              'gists_url': 'https://api.github.com/users/john/gists{/gist_id}',
              'starred_url': 'https://api.github.com/users/john/starred{/owner}{/repo}',
              'subscriptions_url': 'https://api.github.com/users/john/subscriptions',
              'organizations_url': 'https://api.github.com/users/john/orgs',
              'repos_url': 'https://api.github.com/users/john/repos',
              'events_url': 'https://api.github.com/users/john/events{/privacy}',
              'received_events_url': 'https://api.github.com/users/john/received_events',
              'type': 'User',
              'site_admin': false
            },
            'html_url': 'https://github.com/john/acts_as_commentable_with_threading',
            'description': 'Similar to acts_as_commentable; however, utilizes awesome_nested_set to provide threaded comments',
            'fork': true,
            'url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading',
            'forks_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/forks',
            'keys_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/keys{/key_id}',
            'collaborators_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/collaborators{/collaborator}',
            'teams_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/teams',
            'hooks_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/hooks',
            'issue_events_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/issues/events{/number}',
            'events_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/events',
            'assignees_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/assignees{/user}',
            'branches_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/branches{/branch}',
            'tags_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/tags',
            'blobs_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/git/blobs{/sha}',
            'git_tags_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/git/tags{/sha}',
            'git_refs_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/git/refs{/sha}',
            'trees_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/git/trees{/sha}',
            'statuses_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/statuses/{sha}',
            'languages_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/languages',
            'stargazers_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/stargazers',
            'contributors_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/contributors',
            'subscribers_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/subscribers',
            'subscription_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/subscription',
            'commits_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/commits{/sha}',
            'git_commits_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/git/commits{/sha}',
            'comments_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/comments{/number}',
            'issue_comment_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/issues/comments{/number}',
            'contents_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/contents/{+path}',
            'compare_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/compare/{base}...{head}',
            'merges_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/merges',
            'archive_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/{archive_format}{/ref}',
            'downloads_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/downloads',
            'issues_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/issues{/number}',
            'pulls_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/pulls{/number}',
            'milestones_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/milestones{/number}',
            'notifications_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/notifications{?since,all,participating}',
            'labels_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/labels{/name}',
            'releases_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/releases{/id}',
            'deployments_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/deployments',
            'created_at': '2014-08-19T04:47:20Z',
            'updated_at': '2014-08-09T22:56:32Z',
            'pushed_at': '2014-08-13T18:12:05Z',
            'git_url': 'git://github.com/john/acts_as_commentable_with_threading.git',
            'ssh_url': 'git@github.com:john/acts_as_commentable_with_threading.git',
            'clone_url': 'https://github.com/john/acts_as_commentable_with_threading.git',
            'svn_url': 'https://github.com/john/acts_as_commentable_with_threading',
            'homepage': '',
            'size': 150,
            'stargazers_count': 0,
            'watchers_count': 0,
            'language': null,
            'has_issues': false,
            'has_projects': true,
            'has_downloads': true,
            'has_wiki': true,
            'has_pages': false,
            'forks_count': 0,
            'mirror_url': null,
            'archived': false,
            'disabled': false,
            'open_issues_count': 0,
            'license': {
              'key': 'mit',
              'name': 'MIT License',
              'spdx_id': 'MIT',
              'url': 'https://api.github.com/licenses/mit',
              'node_id': 'MDc6TGljZW5zZTEz'
            },
            'forks': 0,
            'open_issues': 0,
            'watchers': 0,
            'default_branch': 'master'
          }
        ]
      }
    };

    expect(selectRepos(state)).toEqual(
      [
        {
          'id': 207071105,
          'node_id': 'MDEwOlJlcG9zaXRvcnkyMDcwNzExMDU=',
          'name': 'acts-as-taggable-on',
          'full_name': 'john/acts-as-taggable-on',
          'private': false,
          'owner': {
            'login': 'john',
            'id': 1668,
            'node_id': 'MDQ6VXNlcjE2Njg=',
            'avatar_url': 'https://avatars1.githubusercontent.com/u/1668?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/john',
            'html_url': 'https://github.com/john',
            'followers_url': 'https://api.github.com/users/john/followers',
            'following_url': 'https://api.github.com/users/john/following{/other_user}',
            'gists_url': 'https://api.github.com/users/john/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/john/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/john/subscriptions',
            'organizations_url': 'https://api.github.com/users/john/orgs',
            'repos_url': 'https://api.github.com/users/john/repos',
            'events_url': 'https://api.github.com/users/john/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/john/received_events',
            'type': 'User',
            'site_admin': false
          },
          'html_url': 'https://github.com/john/acts-as-taggable-on',
          'description': 'A tagging plugin for Rails applications that allows for custom tagging along dynamic contexts.',
          'fork': true,
          'url': 'https://api.github.com/repos/john/acts-as-taggable-on',
          'forks_url': 'https://api.github.com/repos/john/acts-as-taggable-on/forks',
          'keys_url': 'https://api.github.com/repos/john/acts-as-taggable-on/keys{/key_id}',
          'collaborators_url': 'https://api.github.com/repos/john/acts-as-taggable-on/collaborators{/collaborator}',
          'teams_url': 'https://api.github.com/repos/john/acts-as-taggable-on/teams',
          'hooks_url': 'https://api.github.com/repos/john/acts-as-taggable-on/hooks',
          'issue_events_url': 'https://api.github.com/repos/john/acts-as-taggable-on/issues/events{/number}',
          'events_url': 'https://api.github.com/repos/john/acts-as-taggable-on/events',
          'assignees_url': 'https://api.github.com/repos/john/acts-as-taggable-on/assignees{/user}',
          'branches_url': 'https://api.github.com/repos/john/acts-as-taggable-on/branches{/branch}',
          'tags_url': 'https://api.github.com/repos/john/acts-as-taggable-on/tags',
          'blobs_url': 'https://api.github.com/repos/john/acts-as-taggable-on/git/blobs{/sha}',
          'git_tags_url': 'https://api.github.com/repos/john/acts-as-taggable-on/git/tags{/sha}',
          'git_refs_url': 'https://api.github.com/repos/john/acts-as-taggable-on/git/refs{/sha}',
          'trees_url': 'https://api.github.com/repos/john/acts-as-taggable-on/git/trees{/sha}',
          'statuses_url': 'https://api.github.com/repos/john/acts-as-taggable-on/statuses/{sha}',
          'languages_url': 'https://api.github.com/repos/john/acts-as-taggable-on/languages',
          'stargazers_url': 'https://api.github.com/repos/john/acts-as-taggable-on/stargazers',
          'contributors_url': 'https://api.github.com/repos/john/acts-as-taggable-on/contributors',
          'subscribers_url': 'https://api.github.com/repos/john/acts-as-taggable-on/subscribers',
          'subscription_url': 'https://api.github.com/repos/john/acts-as-taggable-on/subscription',
          'commits_url': 'https://api.github.com/repos/john/acts-as-taggable-on/commits{/sha}',
          'git_commits_url': 'https://api.github.com/repos/john/acts-as-taggable-on/git/commits{/sha}',
          'comments_url': 'https://api.github.com/repos/john/acts-as-taggable-on/comments{/number}',
          'issue_comment_url': 'https://api.github.com/repos/john/acts-as-taggable-on/issues/comments{/number}',
          'contents_url': 'https://api.github.com/repos/john/acts-as-taggable-on/contents/{+path}',
          'compare_url': 'https://api.github.com/repos/john/acts-as-taggable-on/compare/{base}...{head}',
          'merges_url': 'https://api.github.com/repos/john/acts-as-taggable-on/merges',
          'archive_url': 'https://api.github.com/repos/john/acts-as-taggable-on/{archive_format}{/ref}',
          'downloads_url': 'https://api.github.com/repos/john/acts-as-taggable-on/downloads',
          'issues_url': 'https://api.github.com/repos/john/acts-as-taggable-on/issues{/number}',
          'pulls_url': 'https://api.github.com/repos/john/acts-as-taggable-on/pulls{/number}',
          'milestones_url': 'https://api.github.com/repos/john/acts-as-taggable-on/milestones{/number}',
          'notifications_url': 'https://api.github.com/repos/john/acts-as-taggable-on/notifications{?since,all,participating}',
          'labels_url': 'https://api.github.com/repos/john/acts-as-taggable-on/labels{/name}',
          'releases_url': 'https://api.github.com/repos/john/acts-as-taggable-on/releases{/id}',
          'deployments_url': 'https://api.github.com/repos/john/acts-as-taggable-on/deployments',
          'created_at': '2019-09-08T06:23:42Z',
          'updated_at': '2019-09-08T06:24:54Z',
          'pushed_at': '2019-09-08T06:24:50Z',
          'git_url': 'git://github.com/john/acts-as-taggable-on.git',
          'ssh_url': 'git@github.com:john/acts-as-taggable-on.git',
          'clone_url': 'https://github.com/john/acts-as-taggable-on.git',
          'svn_url': 'https://github.com/john/acts-as-taggable-on',
          'homepage': 'http://mbleigh.lighthouseapp.com/projects/10116-acts-as-taggable-on',
          'size': 1155,
          'stargazers_count': 0,
          'watchers_count': 0,
          'language': 'Ruby',
          'has_issues': false,
          'has_projects': true,
          'has_downloads': true,
          'has_wiki': true,
          'has_pages': false,
          'forks_count': 1,
          'mirror_url': null,
          'archived': false,
          'disabled': false,
          'open_issues_count': 0,
          'license': {
            'key': 'other',
            'name': 'Other',
            'spdx_id': 'NOASSERTION',
            'url': null,
            'node_id': 'MDc6TGljZW5zZTA='
          },
          'forks': 1,
          'open_issues': 0,
          'watchers': 0,
          'default_branch': 'master'
        },
        {
          'id': 23097215,
          'node_id': 'MDEwOlJlcG9zaXRvcnkyMzA5NzIxNQ==',
          'name': 'acts_as_commentable_with_threading',
          'full_name': 'john/acts_as_commentable_with_threading',
          'private': false,
          'owner': {
            'login': 'john',
            'id': 1668,
            'node_id': 'MDQ6VXNlcjE2Njg=',
            'avatar_url': 'https://avatars1.githubusercontent.com/u/1668?v=4',
            'gravatar_id': '',
            'url': 'https://api.github.com/users/john',
            'html_url': 'https://github.com/john',
            'followers_url': 'https://api.github.com/users/john/followers',
            'following_url': 'https://api.github.com/users/john/following{/other_user}',
            'gists_url': 'https://api.github.com/users/john/gists{/gist_id}',
            'starred_url': 'https://api.github.com/users/john/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/john/subscriptions',
            'organizations_url': 'https://api.github.com/users/john/orgs',
            'repos_url': 'https://api.github.com/users/john/repos',
            'events_url': 'https://api.github.com/users/john/events{/privacy}',
            'received_events_url': 'https://api.github.com/users/john/received_events',
            'type': 'User',
            'site_admin': false
          },
          'html_url': 'https://github.com/john/acts_as_commentable_with_threading',
          'description': 'Similar to acts_as_commentable; however, utilizes awesome_nested_set to provide threaded comments',
          'fork': true,
          'url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading',
          'forks_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/forks',
          'keys_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/keys{/key_id}',
          'collaborators_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/collaborators{/collaborator}',
          'teams_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/teams',
          'hooks_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/hooks',
          'issue_events_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/issues/events{/number}',
          'events_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/events',
          'assignees_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/assignees{/user}',
          'branches_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/branches{/branch}',
          'tags_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/tags',
          'blobs_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/git/blobs{/sha}',
          'git_tags_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/git/tags{/sha}',
          'git_refs_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/git/refs{/sha}',
          'trees_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/git/trees{/sha}',
          'statuses_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/statuses/{sha}',
          'languages_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/languages',
          'stargazers_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/stargazers',
          'contributors_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/contributors',
          'subscribers_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/subscribers',
          'subscription_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/subscription',
          'commits_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/commits{/sha}',
          'git_commits_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/git/commits{/sha}',
          'comments_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/comments{/number}',
          'issue_comment_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/issues/comments{/number}',
          'contents_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/contents/{+path}',
          'compare_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/compare/{base}...{head}',
          'merges_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/merges',
          'archive_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/{archive_format}{/ref}',
          'downloads_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/downloads',
          'issues_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/issues{/number}',
          'pulls_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/pulls{/number}',
          'milestones_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/milestones{/number}',
          'notifications_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/notifications{?since,all,participating}',
          'labels_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/labels{/name}',
          'releases_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/releases{/id}',
          'deployments_url': 'https://api.github.com/repos/john/acts_as_commentable_with_threading/deployments',
          'created_at': '2014-08-19T04:47:20Z',
          'updated_at': '2014-08-09T22:56:32Z',
          'pushed_at': '2014-08-13T18:12:05Z',
          'git_url': 'git://github.com/john/acts_as_commentable_with_threading.git',
          'ssh_url': 'git@github.com:john/acts_as_commentable_with_threading.git',
          'clone_url': 'https://github.com/john/acts_as_commentable_with_threading.git',
          'svn_url': 'https://github.com/john/acts_as_commentable_with_threading',
          'homepage': '',
          'size': 150,
          'stargazers_count': 0,
          'watchers_count': 0,
          'language': null,
          'has_issues': false,
          'has_projects': true,
          'has_downloads': true,
          'has_wiki': true,
          'has_pages': false,
          'forks_count': 0,
          'mirror_url': null,
          'archived': false,
          'disabled': false,
          'open_issues_count': 0,
          'license': {
            'key': 'mit',
            'name': 'MIT License',
            'spdx_id': 'MIT',
            'url': 'https://api.github.com/licenses/mit',
            'node_id': 'MDc6TGljZW5zZTEz'
          },
          'forks': 0,
          'open_issues': 0,
          'watchers': 0,
          'default_branch': 'master'
        }
      ]
    );
  });
});
